apiVersion: v1
kind: Namespace
metadata:
  name: vm-import-ui-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vm-import-ui-sa
  namespace: vm-import-ui-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vm-import-ui-role
rules:
- apiGroups: ["harvesterhci.io"]
  resources: ["virtualmachineimports", "virtualmachineimports/status", "settings"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
- apiGroups: ["network.harvesterhci.io"]
  resources: ["vlanconfigs"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["storage.k8s.io"]
  resources: ["storageclasses"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "watch", "create"]
- apiGroups: ["management.cattle.io"]
  resources: ["projects"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vm-import-ui-rb
subjects:
- kind: ServiceAccount
  name: vm-import-ui-sa
  namespace: vm-import-ui-system
roleRef:
  kind: ClusterRole
  name: vm-import-ui-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vm-import-ui-controller
  namespace: vm-import-ui-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vm-import-ui
  template:
    metadata:
      labels:
        app: vm-import-ui
    spec:
      serviceAccountName: vm-import-ui-sa
      containers:
      - name: vm-import-ui
        image: your-docker-registry/vm-import-ui:0.3.2
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: vm-import-ui-service
  namespace: vm-import-ui-system
spec:
  selector:
    app: vm-import-ui
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vm-import-ui-ingress
  namespace: vm-import-ui-system
  annotations:
    "harvesterhci.io/ui-source": "internal"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: vm-import-ui-service
            port:
              number: 80