// pkg/export.go
//
// VM export orchestration. Phase 2 ships the read-only descriptor preview; the
// job/conversion machinery lands in phase 3.
package main

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"time"

	"github.com/gorilla/mux"
	log "github.com/sirupsen/logrus"
	batchv1 "k8s.io/api/batch/v1"
	v1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/api/resource"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// ExportPreviewRequest asks for the OVF descriptor a given VM would produce.
type ExportPreviewRequest struct {
	Namespace    string `json:"namespace"`
	Name         string `json:"name"`
	Profile      string `json:"profile"`
	PreserveMACs bool   `json:"preserveMacs"`
	GuestOSID    string `json:"guestOsId,omitempty"`
	GuestOSName  string `json:"guestOsName,omitempty"`
}

// previewNotice is prepended to preview descriptors. Disk file sizes are only
// known once qemu-img has produced the converted disks, so a preview omits
// ovf:size and ovf:populatedSize rather than inventing numbers.
const previewNotice = `<!--
  PREVIEW ONLY - generated by vm-import-ui.
  ovf:size and ovf:populatedSize are omitted here because the converted disk
  sizes are not known until the export runs. Everything else matches what the
  real export will emit for this VM and profile.
-->
`

// PreviewOVFHandler renders the OVF descriptor for a VM without touching the
// cluster beyond a read. It is the fastest way to inspect what an export would
// produce, and the feed for `xmllint --schema` / `ovftool --schemaValidate`.
func PreviewOVFHandler(clients *K8sClients) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var req ExportPreviewRequest
		if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
			respondWithError(w, http.StatusBadRequest, "Invalid request body: "+err.Error())
			return
		}
		if req.Namespace == "" || req.Name == "" {
			respondWithError(w, http.StatusBadRequest, "namespace and name are required")
			return
		}
		profile := Profile(req.Profile)
		if profile == "" {
			profile = ProfileVMware
		}
		rules, err := rulesFor(profile)
		if err != nil {
			respondWithError(w, http.StatusBadRequest, err.Error())
			return
		}

		ctx := r.Context()
		vm, err := clients.Dynamic.Resource(vmGVR).Namespace(req.Namespace).Get(ctx, req.Name, metav1.GetOptions{})
		if err != nil {
			log.Errorf("Preview: failed to get VM %s/%s: %v", req.Namespace, req.Name, err)
			respondWithError(w, http.StatusNotFound, "Failed to get VirtualMachine: "+err.Error())
			return
		}

		// Reuse the inventory mapper so the preview cannot drift from what the
		// Export page shows. Run state is irrelevant to the descriptor, so pass
		// an empty set rather than listing VMIs.
		node := harvesterVMToNode(vm, map[string]bool{}, pvcIndex(ctx, clients))

		in := ovfInputFromNode(node, rules)
		in.PreserveMACs = req.PreserveMACs
		in.GuestOSID = req.GuestOSID
		in.GuestOSName = req.GuestOSName

		descriptor, err := BuildOVF(in, profile)
		if err != nil {
			respondWithError(w, http.StatusUnprocessableEntity, "Failed to build OVF descriptor: "+err.Error())
			return
		}

		// Keep the XML declaration first; the notice goes after it.
		out := descriptor
		if i := strings.Index(string(descriptor), "\n"); i >= 0 {
			out = []byte(string(descriptor[:i+1]) + previewNotice + string(descriptor[i+1:]))
		}

		w.Header().Set("Content-Type", "text/xml; charset=utf-8")
		w.WriteHeader(http.StatusOK)
		if _, err := w.Write(out); err != nil {
			log.Errorf("Failed to write OVF preview: %v", err)
		}
	}
}

// ovfInputFromNode converts the inventory view of a VM into OVF generator input.
// Disk file sizes are left at zero: they are only known after conversion.
func ovfInputFromNode(node InventoryNode, rules profileRules) OVFInput {
	in := OVFInput{
		Name:         node.Name,
		Namespace:    node.Namespace,
		CPUs:         node.CPU,
		MemoryMB:     node.MemoryMB,
		Firmware:     node.Firmware,
		MachineType:  node.MachineType,
		Architecture: node.Architecture,
		Annotation: fmt.Sprintf("Exported from Harvester by vm-import-ui: %s/%s",
			node.Namespace, node.Name),
	}

	diskIndex := 0
	for _, d := range node.Disks {
		if d.Device == "cdrom" {
			// Declared as an empty drive; the backing ISO is never exported.
			in.CDROMs++
			continue
		}
		if !isExportableDisk(d) {
			// cloud-init volumes are excluded deliberately: they carry
			// credentials. containerDisks are image layers, not VM state.
			continue
		}
		in.Disks = append(in.Disks, OVFDisk{
			Href:          fmt.Sprintf("disk-%d%s", diskIndex, rules.diskExtension),
			CapacityBytes: d.Capacity,
			BusType:       d.BusType,
			BootOrder:     d.BootOrder,
		})
		diskIndex++
	}

	for _, n := range node.Networks {
		in.Networks = append(in.Networks, OVFNetwork{Name: n.Name, Model: n.ID, MAC: n.MAC})
	}
	return in
}

// --- Export lifecycle -------------------------------------------------------

// exportConfig is the deployment-provided configuration for exports.
type exportConfig struct {
	Root          string // where the export volume is mounted in THIS pod ("" = not mounted)
	PVC           string // RWX claim the Job mounts
	Image         string // image the Job runs
	MaxConcurrent int
	TTLSeconds    int32 // 0 = keep finished export Jobs until deleted
	DeadlineSecs  int64
	RunAsUser     *int64
	FSGroup       *int64
	StorageClass  string // storage class for a PVC auto-created in a VM's namespace ("" = cluster default)
	StorageSize   string // size for a PVC auto-created in a VM's namespace
	PodNamespace  string // this pod's own namespace, to tell whether Root refers to a given export's volume
}

func loadExportConfig() exportConfig {
	// The export Job must run as root by default. Source disks are exposed as
	// block devices owned by root:disk, and a freshly provisioned RWX volume is
	// root-owned and mode 755 — so the image's default UID 1001 cannot write to
	// it. These defaults match the chart's; leaving them nil made the behaviour
	// differ between a chart install and any other deployment.
	defaultUser, defaultGroup := int64(0), int64(0)
	c := exportConfig{
		Root:          os.Getenv("EXPORT_ROOT"),
		PVC:           os.Getenv("EXPORT_PVC"),
		Image:         os.Getenv("EXPORT_IMAGE"),
		MaxConcurrent: 2,
		TTLSeconds:    0,
		DeadlineSecs:  6 * 60 * 60,
		RunAsUser:     &defaultUser,
		FSGroup:       &defaultGroup,
		StorageClass:  os.Getenv("EXPORT_STORAGE_CLASS"),
		StorageSize:   os.Getenv("EXPORT_STORAGE_SIZE"),
		PodNamespace:  os.Getenv("POD_NAMESPACE"),
	}
	if c.StorageSize == "" {
		c.StorageSize = "200Gi"
	}
	if v := os.Getenv("EXPORT_MAX_CONCURRENT"); v != "" {
		if n, err := strconv.Atoi(v); err == nil && n > 0 {
			c.MaxConcurrent = n
		}
	}
	if v := os.Getenv("EXPORT_TTL_SECONDS"); v != "" {
		if n, err := strconv.Atoi(v); err == nil && n >= 0 {
			c.TTLSeconds = int32(n)
		}
	}
	if v := os.Getenv("EXPORT_RUN_AS_USER"); v != "" {
		if n, err := strconv.ParseInt(v, 10, 64); err == nil {
			c.RunAsUser = &n
		}
	}
	if v := os.Getenv("EXPORT_FS_GROUP"); v != "" {
		if n, err := strconv.ParseInt(v, 10, 64); err == nil {
			c.FSGroup = &n
		}
	}
	return c
}

// CreateExportRequest is the POST body for starting an export.
type CreateExportRequest struct {
	Namespace    string `json:"namespace"`
	Name         string `json:"name"`
	Profile      string `json:"profile"`
	TargetName   string `json:"targetName,omitempty"`
	PreserveMACs bool   `json:"preserveMacs"`
	GuestOSID    string `json:"guestOsId,omitempty"`
	GuestOSName  string `json:"guestOsName,omitempty"`
}

// CreateExportHandler validates the request, re-checks that the VM is stopped,
// and creates the Job that performs the export.
func CreateExportHandler(clients *K8sClients) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		var req CreateExportRequest
		if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
			respondWithError(w, http.StatusBadRequest, "Invalid request body: "+err.Error())
			return
		}
		if req.Namespace == "" || req.Name == "" {
			respondWithError(w, http.StatusBadRequest, "namespace and name are required")
			return
		}
		profile := Profile(req.Profile)
		if profile == "" {
			profile = ProfileVMware
		}
		rules, err := rulesFor(profile)
		if err != nil {
			respondWithError(w, http.StatusBadRequest, err.Error())
			return
		}

		cfg := loadExportConfig()
		if cfg.PVC == "" || cfg.Image == "" {
			respondWithError(w, http.StatusServiceUnavailable,
				"Export is not configured on this deployment: set export.storage and export.image in the chart values")
			return
		}

		ctx := r.Context()

		// Concurrency cap. With the chart default replicaCount: 1 this is exact;
		// with more replicas it is advisory, not a distributed lock.
		active, err := listExportJobs(ctx, clients)
		if err != nil {
			respondWithError(w, http.StatusInternalServerError, "Failed to list existing exports: "+err.Error())
			return
		}
		running := 0
		for _, j := range active {
			if j.Status.Succeeded == 0 && j.Status.Failed == 0 {
				running++
			}
		}
		if running >= cfg.MaxConcurrent {
			respondWithError(w, http.StatusTooManyRequests,
				fmt.Sprintf("%d exports are already running (limit %d); wait for one to finish", running, cfg.MaxConcurrent))
			return
		}

		vm, err := clients.Dynamic.Resource(vmGVR).Namespace(req.Namespace).Get(ctx, req.Name, metav1.GetOptions{})
		if err != nil {
			respondWithError(w, http.StatusNotFound, "Failed to get VirtualMachine: "+err.Error())
			return
		}

		// Re-check run state here, immediately before creating the Job, rather
		// than trusting what the inventory showed the user minutes ago. Reading
		// an attached RWX block volume yields a torn image and nothing in
		// Kubernetes prevents it, so this is the load-bearing safety check.
		running2, err := vmIsRunning(ctx, clients, req.Namespace, req.Name)
		if err != nil {
			respondWithError(w, http.StatusInternalServerError, "Could not determine VM power state: "+err.Error())
			return
		}
		if running2 {
			respondWithError(w, http.StatusConflict,
				"VM is running. Power it off before exporting: reading its disks while they are attached produces a corrupt image.")
			return
		}

		node := harvesterVMToNode(vm, map[string]bool{}, pvcIndex(ctx, clients))
		ovfIn := ovfInputFromNode(node, rules)
		ovfIn.PreserveMACs = req.PreserveMACs
		ovfIn.GuestOSID = req.GuestOSID
		ovfIn.GuestOSName = req.GuestOSName
		if len(ovfIn.Disks) == 0 {
			respondWithError(w, http.StatusUnprocessableEntity, "VM has no PVC-backed disks to export")
			return
		}
		// Surface an unreadable PVC as a clear 422 now, rather than letting the
		// Job start and fail minutes later inside BuildOVF.
		for _, d := range ovfIn.Disks {
			if d.CapacityBytes <= 0 {
				respondWithError(w, http.StatusUnprocessableEntity,
					"Could not determine the capacity of disk "+d.Href+"; check that its PersistentVolumeClaim exists and is readable")
				return
			}
		}

		// Source claims, in the same order as the OVF disks.
		var claims []string
		var diskSpecs []ExportDiskSpec
		i := 0
		for _, d := range node.Disks {
			if !isExportableDisk(d) {
				continue
			}
			claims = append(claims, d.PVCName)
			diskSpecs = append(diskSpecs, ExportDiskSpec{
				DevicePath:    fmt.Sprintf("/dev/vmdisk%d", i),
				CapacityBytes: d.Capacity,
				BusType:       d.BusType,
				BootOrder:     d.BootOrder,
			})
			i++
		}

		// The Job mounts the export volume alongside the VM's own PVCs, so it
		// must live in the VM's namespace — a PVC cannot be mounted across
		// namespaces. Provision one there on first use rather than failing the
		// Job at schedule time with an opaque "persistentvolumeclaim not found".
		if err := ensureExportPVC(ctx, clients, req.Namespace, cfg); err != nil {
			respondWithError(w, http.StatusInternalServerError, err.Error())
			return
		}

		exportID := newExportID()
		target := req.TargetName
		if target == "" {
			target = fmt.Sprintf("%s-%s", slugifyName(req.Name), exportID)
		}

		spec := ExportSpec{
			ExportID:    exportID,
			VMNamespace: req.Namespace,
			VMName:      req.Name,
			TargetName:  target,
			Profile:     string(profile),
			Disks:       diskSpecs,
			OVF:         ovfIn,
		}

		job, err := buildExportJob(spec, ExportJobOptions{
			Namespace:    req.Namespace,
			Image:        cfg.Image,
			ExportPVC:    cfg.PVC,
			SourceClaims: claims,
			TTLSeconds:   cfg.TTLSeconds,
			DeadlineSecs: cfg.DeadlineSecs,
			LogLevel:     os.Getenv("LOG_LEVEL"),
			RunAsUser:    cfg.RunAsUser,
			FSGroup:      cfg.FSGroup,
		})
		if err != nil {
			respondWithError(w, http.StatusInternalServerError, err.Error())
			return
		}

		created, err := clients.Clientset.BatchV1().Jobs(req.Namespace).Create(ctx, job, metav1.CreateOptions{})
		if err != nil {
			log.Errorf("Failed to create export Job for %s/%s: %v", req.Namespace, req.Name, err)
			respondWithError(w, http.StatusInternalServerError, "Failed to create export job: "+err.Error())
			return
		}
		log.Infof("Created export job %s/%s for VM %s (profile %s, %d disk(s))",
			created.Namespace, created.Name, req.Name, profile, len(diskSpecs))

		respondWithJSON(w, http.StatusAccepted, map[string]interface{}{
			"exportId":  exportID,
			"namespace": req.Namespace,
			"jobName":   created.Name,
			"target":    target + ".ova",
			"profile":   string(profile),
		})
	}
}

// ensureExportPVC makes sure the export Job's RWX claim exists in namespace,
// creating it from cfg.StorageClass/cfg.StorageSize if it doesn't. PVCs are
// namespace-scoped, so a Job in a VM's namespace can never mount the PVC this
// pod itself mounts (EXPORT_ROOT) unless the VM happens to live in this pod's
// own namespace — see cfg.PodNamespace / exportView for the read-side of that.
func ensureExportPVC(ctx context.Context, clients *K8sClients, namespace string, cfg exportConfig) error {
	pvcs := clients.Clientset.CoreV1().PersistentVolumeClaims(namespace)
	if _, err := pvcs.Get(ctx, cfg.PVC, metav1.GetOptions{}); err == nil {
		return nil
	} else if !errors.IsNotFound(err) {
		return fmt.Errorf("failed to check export volume %s/%s: %w", namespace, cfg.PVC, err)
	}

	size, err := resource.ParseQuantity(cfg.StorageSize)
	if err != nil {
		return fmt.Errorf("invalid export volume size %q: %w", cfg.StorageSize, err)
	}
	pvc := &v1.PersistentVolumeClaim{
		ObjectMeta: metav1.ObjectMeta{
			Name:      cfg.PVC,
			Namespace: namespace,
			Labels:    map[string]string{exportLabelMarker: "true"},
		},
		Spec: v1.PersistentVolumeClaimSpec{
			AccessModes: []v1.PersistentVolumeAccessMode{v1.ReadWriteMany},
			Resources: v1.ResourceRequirements{
				Requests: v1.ResourceList{v1.ResourceStorage: size},
			},
		},
	}
	if cfg.StorageClass != "" {
		pvc.Spec.StorageClassName = &cfg.StorageClass
	}
	if _, err := pvcs.Create(ctx, pvc, metav1.CreateOptions{}); err != nil && !errors.IsAlreadyExists(err) {
		return fmt.Errorf("failed to create export volume %s/%s: %w", namespace, cfg.PVC, err)
	}
	return nil
}

// vmIsRunning reports whether a VirtualMachineInstance exists for the VM, which
// is the authoritative signal that its volumes are attached.
func vmIsRunning(ctx context.Context, clients *K8sClients, namespace, name string) (bool, error) {
	_, err := clients.Dynamic.Resource(vmiGVRKubevirt).Namespace(namespace).Get(ctx, name, metav1.GetOptions{})
	if err == nil {
		return true, nil
	}
	if errors.IsNotFound(err) {
		return false, nil
	}
	return false, err
}

func listExportJobs(ctx context.Context, clients *K8sClients) ([]batchv1.Job, error) {
	list, err := clients.Clientset.BatchV1().Jobs("").List(ctx, metav1.ListOptions{
		LabelSelector: exportLabelMarker + "=true",
	})
	if err != nil {
		return nil, err
	}
	return list.Items, nil
}

// ListExportsHandler returns every export, newest first, merging each Job with
// the status file its worker writes.
func ListExportsHandler(clients *K8sClients) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		jobs, err := listExportJobs(r.Context(), clients)
		if err != nil {
			respondWithError(w, http.StatusInternalServerError, "Failed to list exports: "+err.Error())
			return
		}
		cfg := loadExportConfig()
		out := make([]map[string]interface{}, 0, len(jobs))
		for i := range jobs {
			out = append(out, exportView(&jobs[i], cfg))
		}
		sort.Slice(out, func(a, b int) bool {
			return fmt.Sprint(out[a]["createdAt"]) > fmt.Sprint(out[b]["createdAt"])
		})
		respondWithJSON(w, http.StatusOK, out)
	}
}

// GetExportHandler returns one export.
func GetExportHandler(clients *K8sClients) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		vars := mux.Vars(r)
		job, err := clients.Clientset.BatchV1().Jobs(vars["namespace"]).Get(r.Context(), exportJobName(vars["id"]), metav1.GetOptions{})
		if err != nil {
			respondWithError(w, http.StatusNotFound, "Export not found: "+err.Error())
			return
		}
		respondWithJSON(w, http.StatusOK, exportView(job, loadExportConfig()))
	}
}

// DeleteExportHandler removes the export Job (and its pods). Pass purge=true to
// delete the produced .ova as well.
func DeleteExportHandler(clients *K8sClients) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		vars := mux.Vars(r)
		ns, id := vars["namespace"], vars["id"]
		cfg := loadExportConfig()

		job, err := clients.Clientset.BatchV1().Jobs(ns).Get(r.Context(), exportJobName(id), metav1.GetOptions{})
		if err != nil {
			respondWithError(w, http.StatusNotFound, "Export not found: "+err.Error())
			return
		}

		if r.URL.Query().Get("purge") == "true" && cfg.Root != "" {
			target := job.Annotations[exportAnnTargetName]
			if target != "" {
				if p, err := safeExportPath(cfg.Root, target+".ova"); err == nil {
					if err := os.Remove(p); err != nil && !os.IsNotExist(err) {
						log.Warnf("Could not delete %s: %v", p, err)
					}
				}
			}
			if p, err := safeExportPath(cfg.Root, filepath.Join(".vm-import-ui", id)); err == nil {
				os.RemoveAll(p)
			}
		}

		policy := metav1.DeletePropagationBackground
		if err := clients.Clientset.BatchV1().Jobs(ns).Delete(r.Context(), exportJobName(id),
			metav1.DeleteOptions{PropagationPolicy: &policy}); err != nil {
			respondWithError(w, http.StatusInternalServerError, "Failed to delete export: "+err.Error())
			return
		}
		respondWithJSON(w, http.StatusOK, map[string]string{"message": "Export deleted"})
	}
}

// exportView merges a Job with the worker's status file into one API object.
func exportView(job *batchv1.Job, cfg exportConfig) map[string]interface{} {
	id := job.Labels[exportLabelID]
	view := map[string]interface{}{
		"exportId":   id,
		"namespace":  job.Namespace,
		"jobName":    job.Name,
		"vmName":     job.Annotations[exportAnnVMName],
		"profile":    job.Annotations[exportAnnProfile],
		"targetName": job.Annotations[exportAnnTargetName],
		"createdAt":  job.CreationTimestamp.UTC().Format(time.RFC3339),
		"phase":      jobPhase(job),
	}
	if !exportVolumeMountedHere(job.Namespace, cfg) {
		// The Job's export PVC lives in job.Namespace, which this pod does not
		// mount (see ensureExportPVC) — reading progress or serving a download
		// would silently read the wrong volume, so say so instead of omitting
		// the fields without explanation.
		view["downloadable"] = false
		view["volumeNote"] = fmt.Sprintf(
			"export volume for namespace %q is not mounted in this pod; fetch the OVA from the export share directly",
			job.Namespace)
		return view
	}
	if s, err := readExportStatus(cfg.Root, id); err == nil {
		// The status file is more precise than the Job's coarse phase, but the
		// Job is authoritative about failure: a worker killed outright never
		// gets to record it.
		view["stage"] = s.Stage
		view["percent"] = s.Percent
		view["bytesTotal"] = s.BytesTotal
		view["bytesDone"] = s.BytesDone
		view["sizeBytes"] = s.SizeBytes
		view["chunked"] = s.Chunked
		if s.Error != "" {
			view["error"] = s.Error
		}
		if job.Status.Failed == 0 && s.Phase != "" {
			view["phase"] = s.Phase
		}
		if s.OvaPath != "" {
			view["ovaPath"] = s.OvaPath
			view["downloadable"] = true
		}
	}
	return view
}

// exportVolumeMountedHere reports whether this pod's EXPORT_ROOT mount is the
// same physical volume the export Job in jobNamespace wrote to. PVCs are
// namespace-scoped, so that's only true when the Job ran in this pod's own
// namespace — every other namespace got its own PVC via ensureExportPVC.
// cfg.PodNamespace unset (e.g. running out-of-cluster in dev) is treated as
// "trust cfg.Root", matching the historical single-namespace behaviour.
func exportVolumeMountedHere(jobNamespace string, cfg exportConfig) bool {
	if cfg.Root == "" {
		return false
	}
	if cfg.PodNamespace == "" {
		return true
	}
	return jobNamespace == cfg.PodNamespace
}

func jobPhase(job *batchv1.Job) string {
	switch {
	case job.Status.Succeeded > 0:
		return PhaseReady
	case job.Status.Failed > 0:
		return PhaseFailed
	case job.Status.Active > 0:
		return PhaseConverting
	default:
		return PhasePending
	}
}

func readExportStatus(root, id string) (*ExportStatus, error) {
	if root == "" || id == "" {
		return nil, fmt.Errorf("export volume not mounted in this pod")
	}
	p, err := safeExportPath(root, filepath.Join(".vm-import-ui", id, "status.json"))
	if err != nil {
		return nil, err
	}
	b, err := os.ReadFile(p)
	if err != nil {
		return nil, err
	}
	var s ExportStatus
	if err := json.Unmarshal(b, &s); err != nil {
		return nil, err
	}
	return &s, nil
}

// safeExportPath resolves rel inside root and refuses anything that escapes it.
// Export target names come from user input, so this is the traversal guard.
func safeExportPath(root, rel string) (string, error) {
	if root == "" {
		return "", fmt.Errorf("export root is not configured")
	}
	clean := filepath.Clean(filepath.Join(root, rel))
	rootClean := filepath.Clean(root)
	if clean != rootClean && !strings.HasPrefix(clean, rootClean+string(os.PathSeparator)) {
		return "", fmt.Errorf("path %q escapes the export root", rel)
	}
	return clean, nil
}

// slugifyName lowercases and strips a name down to an RFC-1123-safe token, so it
// is usable in both a Kubernetes object name and a tar member name.
func slugifyName(s string) string {
	s = strings.ToLower(s)
	var b strings.Builder
	for _, r := range s {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9':
			b.WriteRune(r)
		case r == '-' || r == '.' || r == '_' || r == ' ':
			b.WriteRune('-')
		}
	}
	out := strings.Trim(b.String(), "-")
	if out == "" {
		out = "vm"
	}
	if len(out) > 40 {
		out = strings.Trim(out[:40], "-")
	}
	return out
}

func newExportID() string {
	b := make([]byte, 6)
	if _, err := rand.Read(b); err != nil {
		return fmt.Sprintf("%d", time.Now().UnixNano())
	}
	return hex.EncodeToString(b)
}

// DownloadExportHandler serves a finished .ova.
//
// http.ServeContent gives Range support and correct Content-Length without ever
// buffering the file, which matters because these are multi-gigabyte artifacts.
func DownloadExportHandler(clients *K8sClients) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		vars := mux.Vars(r)
		cfg := loadExportConfig()
		if cfg.Root == "" {
			respondWithError(w, http.StatusServiceUnavailable,
				"The export volume is not mounted in this pod; fetch the OVA from the export share directly")
			return
		}
		job, err := clients.Clientset.BatchV1().Jobs(vars["namespace"]).Get(r.Context(), exportJobName(vars["id"]), metav1.GetOptions{})
		if err != nil {
			respondWithError(w, http.StatusNotFound, "Export not found: "+err.Error())
			return
		}
		if !exportVolumeMountedHere(job.Namespace, cfg) {
			respondWithError(w, http.StatusServiceUnavailable, fmt.Sprintf(
				"The export volume for namespace %q is not mounted in this pod; fetch the OVA from the export share directly",
				job.Namespace))
			return
		}
		target := job.Annotations[exportAnnTargetName]
		if target == "" {
			respondWithError(w, http.StatusNotFound, "Export has no recorded target file")
			return
		}
		// The target name is user-supplied, so resolve it strictly inside root.
		path, err := safeExportPath(cfg.Root, target+".ova")
		if err != nil {
			respondWithError(w, http.StatusBadRequest, err.Error())
			return
		}
		f, err := os.Open(path)
		if err != nil {
			respondWithError(w, http.StatusNotFound, "OVA not found; the export may not have finished")
			return
		}
		defer f.Close()
		st, err := f.Stat()
		if err != nil {
			respondWithError(w, http.StatusInternalServerError, err.Error())
			return
		}

		// Guard the browser-download path server-side: the frontend materialises
		// the response in memory, so a large OVA would kill the tab.
		if max := downloadMaxBytes(); max > 0 && st.Size() > max {
			respondWithError(w, http.StatusRequestEntityTooLarge, fmt.Sprintf(
				"OVA is %d bytes, over the %d byte download limit; copy it from the export share at %s",
				st.Size(), max, path))
			return
		}

		w.Header().Set("Content-Type", "application/x-tar")
		w.Header().Set("Content-Disposition", fmt.Sprintf("attachment; filename=%q", target+".ova"))
		http.ServeContent(w, r, target+".ova", st.ModTime(), f)
	}
}

func downloadMaxBytes() int64 {
	if v := os.Getenv("EXPORT_DOWNLOAD_MAX_BYTES"); v != "" {
		if n, err := strconv.ParseInt(v, 10, 64); err == nil {
			return n
		}
	}
	return 2 << 30 // 2 GiB
}

// GetExportLogsHandler tails the export Job's pod logs. It mirrors the existing
// plan-log handler, and is the fallback when the status file is unavailable.
func GetExportLogsHandler(clients *K8sClients) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		vars := mux.Vars(r)
		ns, id := vars["namespace"], vars["id"]
		ctx := r.Context()

		pods, err := clients.Clientset.CoreV1().Pods(ns).List(ctx, metav1.ListOptions{
			LabelSelector: exportLabelID + "=" + id,
		})
		if err != nil {
			respondWithError(w, http.StatusInternalServerError, "Failed to list export pods: "+err.Error())
			return
		}
		if len(pods.Items) == 0 {
			respondWithError(w, http.StatusNotFound, "No pod found for this export (it may have been cleaned up)")
			return
		}

		tail := int64(500)
		var out strings.Builder
		for i := range pods.Items {
			pod := &pods.Items[i]
			fmt.Fprintf(&out, "=== pod %s (%s) ===\n", pod.Name, pod.Status.Phase)
			req := clients.Clientset.CoreV1().Pods(ns).GetLogs(pod.Name, &v1.PodLogOptions{TailLines: &tail})
			stream, err := req.Stream(ctx)
			if err != nil {
				fmt.Fprintf(&out, "could not read logs: %v\n", err)
				continue
			}
			b, err := io.ReadAll(stream)
			stream.Close()
			if err != nil {
				fmt.Fprintf(&out, "could not read logs: %v\n", err)
				continue
			}
			out.Write(b)
			out.WriteString("\n")
		}

		w.Header().Set("Content-Type", "text/plain; charset=utf-8")
		w.WriteHeader(http.StatusOK)
		if _, err := w.Write([]byte(out.String())); err != nil {
			log.Errorf("Failed to write export logs: %v", err)
		}
	}
}
