name: Docker Image CI to GHCR

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    # 1. Set up QEMU for emulation
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    # 2. Set up Docker Buildx
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push amd64
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: ghcr.io/doccaz/vm-import-ui:latest
        platforms: linux/amd64
    - name: Build and push ARM64
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: ghcr.io/doccaz/vm-import-ui:latest
        platforms: linux/arm64
