name: Docker Image CI to GHCR

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    # QEMU is no longer needed, so we remove this step
    # - name: Set up QEMU
    #   uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Combine both platforms into a single build and push step
    - name: Build and push Multi-Platform Image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        # List all target platforms here
        platforms: linux/amd64,linux/arm64
        tags: ghcr.io/doccaz/vm-import-ui:latest
        # Optional but highly recommended: add caching to speed up builds
        cache-from: type=gha,scope=build-vm-import-ui
        cache-to: type=gha,scope=build-vm-import-ui,mode=max
